services:
  - type: web
    name: igdashboard-backend
    env: node
    rootDir: server/server
    buildCommand: "npm install"
    startCommand: "node server.js"
    plan: free
    envVars:
      - key: PORT
        value: "5000"
      - key: MONGO_URI
        value: "mongodb+srv://Nezer123:Nezer123@cluster0.gxwzytz.mongodb.net/IGDashboard?retryWrites=true&w=majority"
      - key: APP_ID
        value: "25028890196796898"
      - key: APP_SECRET
        value: "66b8f29aaf8e69be57e9493429d30a09"
      - key: VERIFY_TOKEN
        value: "ejswebhook123"
      - key: CALLBACK_URL
        value: "https://stalagmitical-yen-perfidious.ngrok-free.dev/auth/instagram/callback"
